---
driver:
  name: vagrant
  provider: parallels

provisioner:
  name: chef_solo
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: macOS_10124_Sierra
    driver:
      box: macOS_10124_Sierra
      username: admin

suites:
  - name: default
    run_list:
      - recipe[macos-cookbook::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
    customize:
      memory: 8192
      cpus: 4
